name: 60306106 - SM

on:
  schedule:
    # GYM
    - cron: '0 9 * * 1'    # Mon
    - cron: '0 9 * * 2'    # Tues
    - cron: '30 7 * * 3'   # Wednes
    # SWIMMING
    - cron: '0 10 * * 3'   # Wednes
  workflow_dispatch:

jobs:

  # Gym Booking Jobs
  run-booking-Monday-Gym:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Time_Check
        run: |
          if [ "$(date +%H)" == "09" ] && [ "$(date +%A)" == "Monday" ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install --upgrade requests
            python gym.py --pa "${{ secrets.PASS_60306106 }}" --i ${{ secrets.ID_60306106 }} --ln ${{ secrets.LAST_NAME_60306106 }} --fn ${{ secrets.FIRST_NAME_60306106 }} --ca 0 --t 12 --fd True
          else
            exit 0
          fi

  run-booking-Tuesday-Gym:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Time_Check
        run: |
          if [ "$(date +%H)" == "09" ] && [ "$(date +%A)" == "Tuesday" ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install --upgrade requests
            python gym.py --pa ${{ secrets.PASS_60306106 }} --i ${{ secrets.ID_60306106 }} --ln ${{ secrets.LAST_NAME_60306106 }} --fn ${{ secrets.FIRST_NAME_60306106 }} --ca 0 --t 10.5 --fd True
          else
            exit 0
          fi

  run-booking-Wednesday-Gym:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Time_Check
        run: |
          if [ "$(date +%H)" == "07" ] && [ "$(date +%A)" == "Wednesday" ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install --upgrade requests
            python gym.py --pa ${{ secrets.PASS_60306106 }} --i ${{ secrets.ID_60306106 }} --ln ${{ secrets.LAST_NAME_60306106 }} --fn ${{ secrets.FIRST_NAME_60306106 }} --ca 0 --t 10.5 --fd True
          else
            exit 0
          fi

  run-booking-Wednesday-Swimming:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Time_Check
        run: |
          if [ "$(date +%H)" == "10" ] && [ "$(date +%A)" == "Wednesday" ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install --upgrade requests
            python gym.py --pa ${{ secrets.PASS_60306106 }} --i ${{ secrets.ID_60306106 }} --ln ${{ secrets.LAST_NAME_60306106 }} --fn ${{ secrets.FIRST_NAME_60306106 }} --ca 1 --t 13 --fd True
          else
            exit 0
          fi
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Time_Check
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install --upgrade requests
            python gym.py --pa "${{ secrets.PASS_60306106 }}" --i ${{ secrets.ID_60306106 }} --ln ${{ secrets.LAST_NAME_60306106 }} --fn ${{ secrets.FIRST_NAME_60306106 }} --ca 0 --t 12 --fd True
