name: Gym Booking Automation

on:
  schedule:
    - cron: '0 12 * * 0'  # Every day at 06:00 UTC
    - cron: '0 13 * * 1'  # Every day at 09:00 UTC
    - cron: '0 11 * * 2'  # Every day at 12:00 UTC
    - cron: '0 15 * * 3'  # Every day at 15:00 UTC
    - cron: '0 13 * * 4'  # Every day at 18:00 UTC
    - cron: '0 15 * * 1'
    - corn: '0 13 * * 2'
    - cron: '0 13 * * 3'
    - cron: '0 13 * * 4'
    
  workflow_dispatch:

jobs:
  run-booking-Sunday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 12 * * 0'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking Sunday
      run: |
        python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 12 --fd True

  run-booking-Monday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 13 * * 1'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking Monday
      run: |
        python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 13 --fd True
        
  run-booking-Monday-Swimming:
      runs-on: ubuntu-latest
      if: github.event.schedule == '0 15 * * 1'
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run Swimming Booking Monday
        run: |
          python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --fn ${{ secrets.ME_FIRST_NAME }} --ln ${{ secrets.ME_LAST_NAME }} --category 1 --time 15 --fd True

  run-booking-Tuesday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 11 * * 2'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 1 (Evening)
      run: |
         python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 11 --fd True
   
  run-booking-Tuesday-Swimming:
      runs-on: ubuntu-latest
      if: github.event.schedule == '0 13 * * 2'
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run Gym Booking for User 1 (Evening)
        run: |
           python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 13 --fd True

  run-booking-Wednesday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 15 * * 3'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 2 (Morning)
      run: |
         python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 15 --fd True
  
  run-booking-Wednesday-Swimming:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 13 * * 3'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 2 (Morning)
      run: |
         python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 1 --time 13 --fd True

  run-booking-Thursday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 15 * * 4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 2 (Afternoon)
      run: |
         python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 12 --fd True
  
  run-booking-Thursday-Swimming:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 13 * * 4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 2 (Afternoon)
      run: |
         python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 1 --time 13 --fd True
