name: Gym And Pool Booking Automation

on:
  schedule:
    - cron: '47 3 * * *'
  workflow_dispatch:
jobs:
  conditional_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get current time and day
      id: currentTimeDay
      run: |
        echo "Current hour: $(date +%H)" >> $GITHUB_OUTPUT
        echo "Current day: $(date +%A)" >> $GITHUB_OUTPUT
        
    - name: Check conditions
      if: steps.currentTimeDay.outputs.CurrentHour == "3" && steps.currentTimeDay.outputs.CurrentDay == "Monday"
      run: |
        echo "It's 1 hour on Monday!"
        # Add your actions here
    
    - name: Alternative action
      if: steps.currentTimeDay.outputs.CurrentHour != "1" || steps.currentTimeDay.outputs.CurrentDay != "Monday"
      run: |
        echo "It's not 1 hour on Monday!"
        # Add alternative actions here
