name: Gym Booking Automation

on:
  schedule:
    - cron: '0 9 * * 0'  # Every day at 06:00 UTC
    - cron: '0 9 * * 1'  # Every day at 09:00 UTC
    - cron: '0 12 * * 2'  # Every day at 12:00 UTC
    - cron: '0 15 * * 3'  # Every day at 15:00 UTC
    - cron: '0 18 * * 4'  # Every day at 18:00 UTC
  workflow_dispatch:

jobs:
  run-booking-user1-morning:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 6 * * 0'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 1 (Morning)
      run: |
        python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 12 --fd True

  run-booking-user1-midday:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 12 * * 1'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 1 (Midday)
      run: |
        python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 13 --fd True
  run-booking-user1-ongod:
      runs-on: ubuntu-latest
      if: github.event.schedule == '0 6 * * 1'
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run Swimming Booking for User 1 (Midday)
        run: |
          python gym.py --pa ${{ secrets.ME_PASS }} --i ${{ secrets.ME_ID }} --fn ${{ secrets.ME_FIRST_NAME }} --ln ${{ secrets.ME_LAST_NAME }} --category 1 --time 15 --fd True

  run-booking-user1-evening:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 18 * * 2'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 1 (Evening)
      run: |
        python gym.py --pa ${{ secrets.USER1_PASSWORD }} --i ${{ secrets.USER1_ID }} --fn User1FirstName --ln User1LastName --category 178388 --time 7.5 --range_time 1.5 --date "$(date +'%b %d, %Y')"

  run-booking-user2-morning:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 9 * * 3'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 2 (Morning)
      run: |
        python /path/to/your/script.py --pa ${{ secrets.USER2_PASSWORD }} --i ${{ secrets.USER2_ID }} --fn User2FirstName --ln User2LastName --category 178388 --time 7.5 --range_time 1.5 --date "$(date +'%b %d, %Y')"

  run-booking-user2-afternoon:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 15 * * 4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gym Booking for User 2 (Afternoon)
      run: |
        python /path/to/your/script.py --pa ${{ secrets.USER2_PASSWORD }} --i ${{ secrets.USER2_ID }} --fn User2FirstName --ln User2LastName --category 178388 --time 7.5 --range_time 1.5 --date "$(date +'%b %d, %Y')"
