name: Gym And Pool Booking Automation

on:
  schedule:
  #GYM
    - cron: '0 9 * * 0'  
    - cron: '18 10 * * 1'  
    - cron: '0 8 * * 2'  
    - cron: '0 12 * * 3'  
    - cron: '0 9 * * 4'
  #SWIMMING
    - cron: '0 12 * * 1'
    - cron: '0 10 * * 2'
    - cron: '0 10 * * 3'
    - cron: '0 10 * * 4'
    
  workflow_dispatch:

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test
        run: echo "hello,world"
        
  run-booking-Sunday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 9 * * 0'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests

    - name: Run Gym Booking Sunday
      run: |
        python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 12 --fd True

  run-booking-Monday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '18 10 * * 1'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests

    - name: Run Gym Booking Monday
      run: |
        python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 13 --fd True
        
  run-booking-Monday-Swimming:
      runs-on: ubuntu-latest
      if: github.event.schedule == '0 12 * * 1'
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade requests
  
      - name: Run Swimming Booking Monday
        run: |
          python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --fn ${{ secrets.ME_FIRST_NAME }} --ln ${{ secrets.ME_LAST_NAME }} --category 1 --time 15 --fd True

  run-booking-Tuesday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 8 * * 2'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests

    - name: Run Gym Booking for User 1 (Evening)
      run: |
         python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 11 --fd True
   
  run-booking-Tuesday-Swimming:
      runs-on: ubuntu-latest
      if: github.event.schedule == '0 10 * * 2'
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade requests
          
      - name: Run Gym Booking for User 1 (Evening)
        run: |
           python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 13 --fd True

  run-booking-Wednesday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 12 * * 3'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests

    - name: Run Gym Booking for User 2 (Morning)
      run: |
         python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 15 --fd True
  
  run-booking-Wednesday-Swimming:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 10 * * 3'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests

    - name: Run Gym Booking for User 2 (Morning)
      run: |
         python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 1 --time 13 --fd True

  run-booking-Thursday-Gym:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 9 * * 4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests

    - name: Run Gym Booking for User 2 (Afternoon)
      run: |
         python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 12 --fd True
  
  run-booking-Thursday-Swimming:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 10 * * 4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests

    - name: Run Swimming Booking for User 2 (Afternoon)
      run: |
         python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 1 --time 13 --fd True
