name: Gym And Pool Booking Automation - 101

on:
  schedule:
    - cron: '0 9 * * 0'  # Sunday Gym
    - cron: '0 10 * * 1'  # Monday Gym
    - cron: '0 8 * * 2'  # Tuesday Gym
    - cron: '0 12 * * 3'  # Wednesday Gym
    - cron: '0 9 * * 4'  # Thursday Gym
    - cron: '0 12 * * 1'  # Monday Swimming
    - cron: '0 10 * * 2'  # Tuesday Swimming
    - cron: '0 10 * * 3'  # Wednesday Swimming
    - cron: '0 10 * * 4'  # Thursday Swimming

  workflow_dispatch:

jobs:

  # Common setup job
  setup:
    runs-on: ubuntu-latest
    outputs:
      current_hour: ${{ steps.get_hour.outputs.current_hour }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Get Current Hour
      id: get_hour
      run: |
        current_hour=$(date +%H)
        current_day=$(date +%A)
        echo "::set-output name=current_hour::$current_hour"
        echo "::set-output name=current_day::$current_day"
    - name: Print Current Hour
      run: echo "Current hour is ${{ steps.get_hour.outputs.current_hour }}" && echo "Current hour is ${{ steps.get_hour.outputs.current_day }}" && pwd && ls -R

  # Gym Booking Jobs
  run-booking-Sunday-Gym:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '09' }} && {{ steps.get_hour.outputs.current_day == 'Sunday' }}
    steps:
    - name: Run Gym Booking Sunday
      run: |
        python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 12 --fd True

  run-booking-Monday-Gym:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '10' }} && {{ steps.get_hour.outputs.current_day == 'Monday' }}
    steps:
    - name: path for file
      run: ls -R && pwd
    - name: Run Gym Booking Monday
      run: python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 13 --fd True

  run-booking-Tuesday-Gym:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '08' }} && {{ steps.get_hour.outputs.current_day == 'Tuesday' }}
    steps:
    - name: Run Gym Booking Tuesday
      run: |
        python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 11 --fd True

  run-booking-Wednesday-Gym:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '12' }} && {{ steps.get_hour.outputs.current_day == 'Wednesday' }}
    steps:
    - name: Run Gym Booking Wednesday
      run: |
        python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 15 --fd True

  run-booking-Thursday-Gym:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '09' }}  && {{ steps.get_hour.outputs.current_day == 'Thursday' }}
    steps:
    - name: Run Gym Booking Thursday
      run: |
        python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 0 --time 12 --fd True

  # Swimming Booking Jobs
  run-booking-Monday-Swimming:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '12' }} && {{ steps.get_hour.outputs.current_day == 'Monday' }}
    steps:
    - name: Run Swimming Booking Monday
      run: |
        python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --fn ${{ secrets.ME_FIRST_NAME }} --ln ${{ secrets.ME_LAST_NAME }} --category 1 --time 15 --fd True

  run-booking-Tuesday-Swimming:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '10' }} && {{ steps.get_hour.outputs.current_day == 'Tuesday' }}
    steps:
    - name: Run Swimming Booking Tuesday
      run: |
        python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 1 --time 13 --fd True

  run-booking-Wednesday-Swimming:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '10' }} && {{ steps.get_hour.outputs.current_day == 'Wednesday' }}
    steps:
    - name: Run Swimming Booking Wednesday
      run: |
        python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 1 --time 13 --fd True

  run-booking-Thursday-Swimming:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '10' }} && {{ steps.get_hour.outputs.current_day == 'Thursday' }}
    steps:
    - name: Run Swimming Booking Thursday
      run: |
        python /home/runner/work/automated-booking-python-udst/automated-booking-python-udst/gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ME_ID }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --category 1 --time 13 --fd True
