name: 60302700-AK
on:
  schedule:
    - cron: '0 9 * * 0'  # Sunday Gym
    - cron: '0 10 * * 1'  # Monday Gym
    - cron: '0 8 * * 2'  # Tuesday Gym
    - cron: '0 12 * * 3'  # Wednesday Gym
    - cron: '0 9 * * 4'  # Thursday Gym
    - cron: '0 12 * * 1'  # Monday Swimming
    - cron: '0 10 * * 2'  # Tuesday Swimming
    - cron: '0 10 * * 3'  # Wednesday Swimming
    - cron: '0 10 * * 4'  # Thursday Swimming
  workflow_dispatch: 
    
jobs:
  get-hour-day:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
  # Gym Booking Jobs
  run-booking-Sunday-Gym:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Sunday
      run: |
          python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 12 --fd True

  run-booking-Monday-Gym:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "10" ] || [ "$(date +%A)" != "Monday" ]; then
          exit 1
          fi
    - name: path for file
      run: ls -R && pwd
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Monday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 13 --fd True

  run-booking-Tuesday-Gym:

    runs-on: ubuntu-latest
    steps:   
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "08" ] || [ "$(date +%A)" != "Tuesday" ]; then
          exit 1
          fi   
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Tuesday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 11 --fd True

  run-booking-Wednesday-Gym:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "12" ] || [ "$(date +%A)" != "Wednesday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Wednesday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 15 --fd True

  run-booking-Thursday-Gym:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Thursday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Thursday 
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 12 --fd True

  # Swimming Booking Jobs
  run-booking-Monday-Swimming:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "12" ] || [ "$(date +%A)" != "Monday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Swimming Booking Monday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --fn ${{ secrets.ME_FIRST_NAME }} --ln ${{ secrets.ME_LAST_NAME }} --ca 1 --t 15 --fd True

  run-booking-Tuesday-Swimming:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "10" ] || [ "$(date +%A)" != "Tuesday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Swimming Booking Tuesday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 1 --t 13 --fd True

  run-booking-Wednesday-Swimming:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "10" ] || [ "$(date +%A)" != "Wednesday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Swimming Booking Wednesday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 1 --t 13 --fd True

  run-booking-Thursday-Swimming:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "10" ] || [ "$(date +%A)" != "Thursday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Swimming Booking Thursday
      run:  python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 1 --t 13 --fd True
