name: Gym And Pool Booking Automation test

on:
  schedule:
    - cron: '0 9 * * 0'  # Sunday Gym
    - cron: '18 10 * * 1'  # Monday Gym
    - cron: '0 8 * * 2'  # Tuesday Gym
    - cron: '0 12 * * 3'  # Wednesday Gym
    - cron: '0 9 * * 4'  # Thursday Gym
    - cron: '0 12 * * 1'  # Monday Swimming
    - cron: '0 10 * * 2'  # Tuesday Swimming
    - cron: '0 10 * * 3'  # Wednesday Swimming
    - cron: '0 10 * * 4'  # Thursday Swimming

  workflow_dispatch:

jobs:
  run-booking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Time and Run Script
      run: |
        # Define the target hour (24-hour format)
        target_hour=12

        # Get the current hour
        current_hour=$(date +%H)

        # Print the current hour for debugging
        echo "Current hour: $current_hour"

        # Compare the current hour with the target hour
        if [ "$current_hour" -eq "$target_hour" ]; then
          echo "The current hour matches the target hour. Running the script..."
          # Run your Python script here
          echo "it works "
        else
          echo "The current hour does not match the target hour. Skipping execution."
        fi
