name: Gym And Pool Booking Automation - 101

on:
  schedule:
    - cron: '0 9 * * 0'  # Sunday Gym
    - cron: '0 10 * * 1'  # Monday Gym
    - cron: '0 8 * * 2'  # Tuesday Gym
    - cron: '0 12 * * 3'  # Wednesday Gym
    - cron: '0 9 * * 4'  # Thursday Gym
    - cron: '0 12 * * 1'  # Monday Swimming
    - cron: '0 10 * * 2'  # Tuesday Swimming
    - cron: '0 10 * * 3'  # Wednesday Swimming
    - cron: '0 10 * * 4'  # Thursday Swimming

  workflow_dispatch:

jobs:
  get-hour-day:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get Current Hour and Day and Save to Files
      run: |
        current_hour=$(date +'%H')
        current_day=$(date +'%A')
        echo "$current_hour" > hour.txt
        echo "$current_day" > day.txt

    - name: Display Contents of Files
      run: |
        cat hour.txt
        cat day.txt
        
  # Gym Booking Jobs
  run-booking-Sunday-Gym:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
        cat hour.txt
    - name: Run Gym Booking Sunday
      run: |
          python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 12 --fd True

  run-booking-Monday-Gym:

    runs-on: ubuntu-latest
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: path for file
      run: ls -R && pwd
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Monday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 13 --fd True

  run-booking-Tuesday-Gym:

    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '08' }} && {{ steps.get_hour.outputs.current_day == 'Tuesday' }}
    steps:   
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi   
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Tuesday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 11 --fd True

  run-booking-Wednesday-Gym:

    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '12' }} && {{ steps.get_hour.outputs.current_day == 'Wednesday' }}
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Wednesday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 15 --fd True

  run-booking-Thursday-Gym:

    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '09' }}  && {{ steps.get_hour.outputs.current_day == 'Thursday' }}
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Gym Booking Thursday 
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 0 --t 12 --fd True

  # Swimming Booking Jobs
  run-booking-Monday-Swimming:

    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '12' }} && {{ steps.get_hour.outputs.current_day == 'Monday' }}
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Swimming Booking Monday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --fn ${{ secrets.ME_FIRST_NAME }} --ln ${{ secrets.ME_LAST_NAME }} --ca 1 --t 15 --fd True

  run-booking-Tuesday-Swimming:

    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '10' }} && {{ steps.get_hour.outputs.current_day == 'Tuesday' }}
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Swimming Booking Tuesday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 1 --t 13 --fd True

  run-booking-Wednesday-Swimming:

    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '10' }} && {{ steps.get_hour.outputs.current_day == 'Wednesday' }}
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Swimming Booking Wednesday
      run: python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 1 --t 13 --fd True

  run-booking-Thursday-Swimming:

    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.current_hour == '10' }} && {{ steps.get_hour.outputs.current_day == 'Thursday' }}
    steps:
    - name: Time_Check
      run: |        
          if [ "$(date +%H)" != "09" ] || [ "$(date +%A)" != "Sunday" ]; then
          exit 1
          fi
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade requests
    - name: Run Swimming Booking Thursday
      run:  python gym.py --pa ${{ secrets.PASS_ME }} --i ${{ secrets.ID_ME }} --ln ${{ secrets.ME_LAST_NAME }} --fn ${{ secrets.ME_FIRST_NAME }} --ca 1 --t 13 --fd True
